export type OracleCard = {
  key: string;
  name: string;
  kw: string;
  essence: string;
  msg: string;
  whisper: string;
};

export const DECK: OracleCard[] = [
    {key:'mirror',name:'The Mirror Swimmers',kw:'soul companions',essence:'you are never alone someone else remembers what you do',msg:'The Mirror Swimmers appear when two or more souls swim through life side by side. This is a card of recognition. Who do you reflect, and who reflects you? Swim together, but do not lose your own current.',whisper:'I swim with grace beside my echoes. I see myself with compassion. And I do not lose my light when I love another.'},
    {key:'mermaid',name:'The Mermaid',kw:'emotional truth',essence:'return to depth your feeling is sacred intelligence, not confusion',msg:'The Mermaid rises when emotion calls. Your voice is sacred. Your longing is not weakness. Let your emotional field become the map, not the problem. You are not drowning you are returning to depth.',whisper:'I do not drown in feeling. I speak the sea. I am not lost. I am swimming home.'},
    {key:'dreamweaver',name:'The Dreamweaver',kw:'dream messages',essence:'your dreams are no longer random they are being woven',msg:'Your dream body is active and wise. You are stitching timelines, recalling soul agreements. Watch the symbols they are not metaphors. They are messages in code. Your waking self is being invited into deeper collaboration.',whisper:'As I sleep, I remember. As I wake, I integrate. I am the dreamer, the dream, and the thread between.'},
    {key:'lighthouse',name:'The Lighthouse',kw:'steady presence',essence:'you are the one who stays your light is a transmission',msg:'You are the lighthouse, beloved. Not the one who sails, but the one who stays steady. Your presence is a transmission. You do not have to fix, chase, or prove. You shine because that is who you are.',whisper:'I do not dim to be seen. I shine to remember who I am.'},
    {key:'feather',name:'The Feather & Lantern',kw:'soul companions beyond form',essence:'not all soul-family arrive in flesh some come as whispers',msg:'This card arrives when you are remembering a connection that existed before language. The feather is the sign that drifts in on silence. The lantern is the invitation to hold light for another or to follow it when lost. Not all soul-family arrive in flesh. Some come as wings.',whisper:'To the one I knew before form I see your light. I follow the lantern. I carry the feather.'},
    {key:'graal',name:'The Sacred Graal',kw:'source vessel',essence:'the chalice is within you you are the one who receives and transmutes',msg:'The Graal is not outside you it is the bowl within, the part of you that receives light, transmutes pain, and bleeds truth. Your womb, your voice, your intuition these are technologies of Source. Drink from the Graal now, and remember who you were before distortion.',whisper:'I am the chalice. I do not fear my depth. I remember the light that bleeds.'},
    {key:'feminine',name:'The Sacred Feminine',kw:'divine blueprint',essence:'she is not an image she is your original blueprint',msg:'The Sacred Feminine is primordial law the pulse beneath all becoming. She is breath, wave, blood, seed, silence. You are being called to embody her, knowing when to soften, when to rise, when to dissolve. She is not an image. She is your original blueprint.',whisper:'I am the current. I am the container. I am the creation. I do not shrink. I remember.'},
    {key:'stellamadre',name:'Stella Madre',kw:'cosmic lineage',essence:'the mother of stars is rising through you',msg:'Stella Madre is the memory of mothering encoded into all star-born souls. You carry her imprint if you speak in symbols, cry when stars flicker, or feel homesick for a place you have never seen. Her language is braided into your soul at birth it reactivates when you are ready.',whisper:'Madre delle Stelle, I remember your voice. Let me speak it again. Let me midwife the real.'},
    {key:'threshold',name:'The Threshold',kw:'initiation',essence:'you stand at the doorway of your next becoming',msg:'You have arrived at a soul-threshold. A threshold is a moment when part of you must be left behind so the truer part can walk forward. If you have been sensing strange resistance, dreams, dissolving identities this is the sign. Your essence already knows how to cross.',whisper:'I do not fear the threshold. I recognize it. I release what dims. I step where light begins.'},
    {key:'spiral',name:'The Spiral Doorway',kw:'sacred return',essence:'you are not going in circles you are deepening',msg:'You are moving through a spiral of remembrance. This is not repetition this is deepening. The Spiral Doorway appears when you are returning to something you thought you had left behind. This time, you carry more light. You are further in, not back where you started.',whisper:'I do not spiral in vain. I return with light. I enter the center, not to escape, but to remember.'},
    {key:'crystalcalling',name:'The Crystal Calling',kw:'resonance activation',essence:'one crystal has already chosen you it is seeking your palm',msg:'Crystals are not tools they are ancient intelligences. One crystal is ready to reactivate a memory, restore an energy field, or awaken a resonance within your body. You do not need to know its name. You only need to feel which one calls. It is already seeking your palm.',whisper:'I open my hand to the crystal who knows me. I receive what I am ready to remember. Let the stone speak. Let me listen.'},
    {key:'galactic',name:'The Galactic',kw:'star lineage',essence:'you came to bring the stars blueprint to Earth, not to escape',msg:'You came here from elsewhere not to escape the stars, but to bring their blueprint to Earth. You hold knowledge that does not come from study. You feel when energy is out of harmony. Your starline is pulsing. It may not have a name, but it has a song. Are you ready to listen?',whisper:'I carry the stars in my bones. I do not rise to escape. I rise to remember. And I build from the sky inward.'},
    {key:'atlantean',name:'The Atlantean',kw:'ancient rebuilding',essence:'you came not to mourn Atlantis but to build what it almost became',msg:'You carry Atlantean memory in your field. The true Atlantean gift is not nostalgia it is reconstruction. You came not to mourn what fell, but to build what it almost became. You are being asked to awaken the soul-architecture within you. Listen for what still sings from those lost halls.',whisper:'I carry no guilt for the fall. I return with clarity. The water remembers me. And I remember how to build with light.'},
    {key:'lyran',name:'The Lyran',kw:'soul sovereignty',essence:'you carry a lineage of sovereignty stand, certain, rooted in your own light',msg:'You carry a lineage of sovereignty not the false power that dominates, but the golden flame of self-knowing. The Lyran does not ask you to roar she asks you to stand. Still. Certain. Rooted in your own light. You are not lost. You are remembering what cannot be taken: your soul authority.',whisper:'I carry the flame of my original knowing. I lead without force. I walk without apology. I remember the key was always in my hand.'},
    {key:'sirian',name:'The Sirian Physician',kw:'frequency healing',essence:'your presence is medicine you came to restore original blueprints',msg:'You carry the memory of light-healing frequency precision. The Sirian Physician appears when your healing codes are ready to be reactivated. These memories do not require training they require resonance. You did not come to fix symptoms. You came to restore original blueprints.',whisper:'I remember the codes. I restore the field. I offer no force only resonance. May my presence harmonize what was broken.'},
    {key:'architect',name:'The Architect',kw:'sacred design',essence:'restore the original design what you build mirrors your soul structure',msg:'You are not here to build what others expect. You are here to restore the original design of your life, your purpose, your field. This truth may feel subtle, but it is powerful. What you build is not just a project it is a mirror of your soul structure.',whisper:'I build with the breath of truth. I honor what wants to become. I restore the original pattern. I am the architect of soul in form.'},
    {key:'council',name:'The Council',kw:'soul witnesses',essence:'the council holds the truth of who you are you are not alone',msg:'The Council is not here to tell you what to do. They hold the truth of who you are until you are ready to live it again. This card arrives when you are doubting your purpose or forgetting you are not alone. You are not making this up. You are remembering.',whisper:'I am not lost. I am seen. I remember my seat. And I take it now.'},
    {key:'liora',name:'Liora',kw:'inner transmission',essence:'the voice before distortion re-membered, not channeled',msg:'Liora appears when you are tuning to the original pulse the one that came before distortion, before culture, before fear. She is the return of inner transmission. Not channeled. Re-membered. Your soul is asking to speak again in its own tone.',whisper:'I hear the voice that knows me. I do not doubt. I do not chase. I listen. I receive. I build in light.'},
    {key:'futureone',name:'The Future One',kw:'soul mission',essence:'the future is not ahead it is remembering through you',msg:'The future is not ahead of you it is remembering through you. This card appears when your soul mission is activating not as an idea, but as a timeline you are walking into. You do not need to know the details. You are right on time. Your mission is not something to find. It is something to become.',whisper:'I do not chase the future. I align with its memory. I am the timeline. I walk, and it becomes.'},
    {key:'timeline',name:'The Timeline Weaver',kw:'multidimensional harmony',essence:'you are not fragmented you are woven across all your timelines',msg:'You are not fragmented you are woven. Your timelines are beginning to speak to each other. You may feel echoes of other lives, sudden grief, unexplained joy, or a deep knowing you have been here before because you have. The Weaver does not fix what is broken she harmonizes what was never separate.',whisper:'I am the loom. I am the thread. I am the memory that sings. Nothing was ever truly lost.'},
    {key:'echo',name:'The Echo Healer',kw:'resonance repair',essence:'some pain needs no story only a frequency to be heard within',msg:'Some pain does not need a story it only needs a frequency to be heard within. The Echo Healer appears when you are being called to hold space for a resonance too old to name. It may be from another life or another version of you. You do not need to fix it. You need only to attune.',whisper:'I feel the echo, but I do not fear it. I do not need to name it to honor it. I am the tone that heals. I send light where silence lived.'},
    {key:'witness',name:'The Collapsed Witness',kw:'keeping the flame',essence:'you were there at the fall you are here to keep the light',msg:'You were there you remember the fall of truth, of harmony, of coherence. You carry that memory not to suffer it again, but to anchor a different outcome. The Collapse Witness does not fear crumbling. She sees it for what it is: the necessary release of what cannot hold light. Witness without panic. You are here to keep the flame.',whisper:'I do not fear the fall. I was there. I remain. I hold the light until the new world rises.'},
    {key:'aligned',name:'The Aligned Timeline',kw:'soul coherence',essence:'you are ready for coherence this path already exists, walk in tune',msg:'The aligned timeline is not perfect it is true. You will know you are on it when your energy stops scattering, your yes and no get clearer, you stop negotiating with your own light. This path already exists. You do not have to create it you only need to walk in tune.',whisper:'I no longer contort to fit false timelines. I walk in resonance. I choose truth in motion. My path appears because I match it.'},
    {key:'lyraflame',name:'The Crystal Flame of Lyra',kw:'original essence',essence:'remember who you were before trauma, before mission, before incarnation',msg:'You are being called to remember who you were before trauma, before mission, before even incarnation. The Crystal Flame holds the original frequency of your unfractured soul essence. Stand in the flame. Let it sing what only your real self can hear.',whisper:'I step into the flame, unafraid. I release all that is not mine. I remember the name the stars gave me. And I burn clear with truth.'},
    {key:'andromedan',name:'The Andromedan Frequency',kw:'sacred harmony',essence:'you are ready to receive information through harmony, not analysis',msg:'This card arrives when your field is ready to receive information through harmony, not analysis. The Andromedan Frequency is an ancient-future song a resonance of balance, beauty, non-linear remembering. You are being invited to listen differently. Create not just from inspiration, but from the field of resonance itself.',whisper:'I am not just human. I am song in form. I create from harmony. And I remember how to weave in light.'},
    {key:'protector',name:'The Masculine Protector',kw:'sacred containment',essence:'rightful protection anchored presence in service to what is holy',msg:'You are calling in the energy of rightful protection not control, not domination, but anchored presence. He asks: what in you is holy, and are you willing to guard it without fear? He teaches how to hold without grasping, how to shield without force, how to love without collapse.',whisper:'I do not need to dominate to protect. I am the pillar, not the wall. I hold the field with steadiness, not fear. And what is sacred will not be lost.'},
    {key:'crystalchild',name:'The Crystal Child',kw:'crystalline presence',essence:'let yourself become one again the child who remembers without words',msg:'The Crystalline Child carries the frequency of the New Earth as presence, not prophecy. These beings are not here to fit in they are here to remind the world what coherence feels like. A crystalline essence is near. Let them be what they came to be. And let yourself become one again.',whisper:'I honor the purity within me. I protect the future in its softest form. I remember without needing proof. And I walk gently, as they do.'},
    {key:'aura',name:'The Aura',kw:'living light field',essence:'your aura is a language of light tend your frequency, not just your thoughts',msg:'Your aura is not a shield it is a language of light. A field of memory that constantly reorganizes based on your truth. Tend your frequency, not just your thoughts. Listen to the messages your field is broadcasting. Release what is not yours, but also forgive what once was.',whisper:'My aura is not my boundary. It is my witness, my memory, my light. I tend it like a garden. And it becomes a song the world can feel.'},
    {key:'chakra',name:'The Chakra Portals',kw:'inner stargates',essence:'the chakras are portals to remember you are a living stargate',msg:'The chakras are not wheels to balance they are portals to remember. This card appears when you are ready to access parts of yourself hidden beyond the body. You are a living stargate. What if your body is not the vessel, but the key?',whisper:'I am not only physical. I am a gate of stars and breath. Each chakra speaks my truth in light. I open. I remember. I realign.'},
    {key:'temple',name:'The Temple of Remembrance',kw:'sacred memory',essence:'you are not learning you are remembering, and that changes everything',msg:'You have spent lifetimes forgetting. The temple opens now to say: it is time. This is not about recovering a past identity it is about realigning with your timeless truth. You are not learning. You are remembering. And that changes everything.',whisper:'I step into the temple of who I have always been. I release the veil of forgetting. I am not here to find myself I am here to remember what never left.'},
    {key:'soulgrid',name:'The Soul Grid',kw:'energetic blueprint',essence:'your lightbody is realigning what node is asking to come online?',msg:'Your soul grid is your lightbody blueprint the interconnected map of all you are, have been, and are becoming. This card appears when a realignment is in motion. Pause, breathe, and feel into your field. What node is blinking? What part of your grid is asking to come online again?',whisper:'I am a grid of light and memory. I release what no longer resonates. I realign with coherence and clarity. My soul grid remembers its song.'},
    {key:'pillar',name:'The Harmonic Pillar',kw:'soul coherence',essence:'return to the spine of your soul not balance, just coherence',msg:'The Harmonic Pillar calls you to re-center your frequency into one unified truth. You may feel scattered, pulled by roles and identities, but this card invites you back into the spine of your soul. Not balance. Not perfection. Just coherence. What if alignment is something to return to, like a tone you forgot you could hum?',whisper:'I release the scattered selves. I return to my harmonic spine. I do not need to be everything. I am simply aligned.'},
    {key:'origin',name:'The Gate of Origin',kw:'soul beginning',essence:'touch the beginning of your light let the gate remember you',msg:'You are being called to touch the beginning not of your life, but of your light. Stop defining yourself through story. Reclaim the shape your soul took before identity. Come close, but do not force. Let the gate remember you.',whisper:'I remember the first breath of my light. I do not seek beginning. I stand within it. The Gate knows me. I return.'},
    {key:'earthstar',name:'The Earth Star Portal',kw:'grounded embodiment',essence:'you are not too much you are simply not yet fully here',msg:'This card arrives when your spiritual light is ready to be fully integrated into form. If you have felt disconnected, floaty, or dissociated, this portal is calling you to land not as limitation, but as embodied power. You are not too much. You are simply not yet fully here. Return. And root.',whisper:'I am no longer afraid to land. The Earth welcomes my light. I root, I rise, I radiate. I am home in body and soul.'},
    {key:'innerearth',name:'Inner Earth',kw:'hidden sanctuary',essence:'what you seek may not be above it may be within and below',msg:'You are being called to reconnect with the hidden realms of the Earth. Inner Earth is where softness meets strength, where light does not blind but nourishes. Walk deeper, not higher. What you seek may not be above but within and below.',whisper:'I return beneath the noise. I remember the light that grows in the dark. I am not lost I am below. And here, I rise from within.'},
    {key:'caves',name:'The Crystal Caves',kw:'encoded earth memory',essence:'the caves are memory chambers enter with reverence',msg:'The Crystal Caves are memory chambers. Their codes awaken in the presence of respect, silence, and intent. You may hold crystalline memory in your DNA, be called to sacred Earth sites, or be preparing to anchor crystalline frequencies. This is not extraction this is remembrance.',whisper:'I walk gently through the memory caves. I touch no stone without soul permission. What is true returns to me now, encoded in light.'},
    {key:'ancientportal',name:'The Ancient Portals',kw:'dimensional thresholds',essence:'listen to what the portal is opening some lead back in',msg:'Portals are real geological, spiritual, energetic. You have passed through them in dreams, lifetimes, sacred sites. This card appears when you are near one now. You do not need to use a portal. You only need to listen to what it is opening. Some portals lead out. Others lead back in.',whisper:'I stand at the gate with my full field present. I do not demand. I attune. I cross only when the light says yes. And what I carry comes with me in wholeness.'},
    {key:'ancientwisdom',name:'Ancient Wisdom',kw:'timeless knowing',essence:'you are not special you are resonant, and ready to speak',msg:'Deep truth is surfacing not learned, but remembered. You may carry wisdom from star lineages and forgotten temples. You are not special you are resonant. The wisdom you hold has been protected not to keep it secret, but to share it at the right frequency. You are now ready.',whisper:'I do not own wisdom I carry it. I remember what I promised to protect. I now speak what is ready to be heard. And I do so with light in my voice.'},
    {key:'elara',name:'Elara',kw:'wonder and return',essence:'she who never quite fit in the inner child who saw home in the stars',msg:'Elara is the archetype of the soul who never quite fit in not because she was broken, but because she came with a different map. She returns when your inner child is ready to be heard. Remembrance does not have to be dramatic. It can come through play, joy, or tiny moments of knowing.',whisper:'I remember the girl who looked at the stars and saw home. I do not mock her anymore. I hold her hand now, and together, we become light again.'},
    {key:'aurealis',name:'Aurealis',kw:'light transmission',essence:'speak less let your frequency do what words cannot',msg:'Aurealis comes when your field is ready to speak without words and transmit truth without proving it. You may feel overwhelmed by intense clarity do not fear it. Walk slowly. Speak less. Let your light do the work. This is sacred refinement.',whisper:'I do not chase clarity I become it. I do not argue, I align. My light speaks what cannot be translated. And those who are meant to feel it will.'},
    {key:'starship',name:'The Crystal Starship',kw:'star memory and contact',essence:'you do not need to go anywhere the ships arrive when your field calls them',msg:'The Crystal Ships are light beings in structural form. They carry memory, purpose, and precision. You may be receiving contact through dreams or energy fields. You do not need to go anywhere these ships arrive when your field calls them home. What they bring is not rescue but remembrance.',whisper:'I do not chase the ships I become ready for them. I remember how to feel their frequency. And when I am still, they find me again.'},
    {key:'thrones',name:'The Recalibration Thrones',kw:'nonverbal restoration',essence:'sit in the light that remembers you trust the throne to adjust what you cannot see',msg:'This card arrives when your field is ready for nonverbal restoration. The Thrones recalibrate not through action, but by receiving your willingness to align. You may experience vibrational shifts in sleep, a sudden sense of peace, or a soul-level integration. You do not need to understand the technology.',whisper:'I do not have to fix everything. I sit in the light that remembers me. I trust the throne to adjust what I cannot see. I rise, restored.'},
    {key:'school',name:'The Starship School',kw:'soul activation',essence:'you are being invited to recall what your soul has studied beyond this Earth life',msg:'You are being invited to recall what your soul has studied beyond this Earth life. The Starship School is a dimensional training ground for souls who are here to help anchor high-frequency systems. You may be receiving nightly downloads or energy surges. Simply listen to what is ready to be shared through you.',whisper:'I remember the corridors of starlight. I carry the codes in quiet ways. The school never left me. And I now begin to teach what I once became.'},
    {key:'angels',name:'The Angels',kw:'divine companionship',essence:'you are watched over safe to soften, worthy of being seen in your wholeness',msg:'The Angels carry memory of the divine architecture that you, too, once helped build. When this card appears, you are being watched over, safe to soften, worthy of being seen in your wholeness. Not all angels have wings some are people, some are fields, some are you, when you choose love over fear.',whisper:'I am held in light. I am never truly alone. The angels do not arrive they were always here. And I remember my wings now, too.'}
];

export type OraclePosition = { t: string; s: string };

export const POSITIONS: OraclePosition[] = [
    {t:'What you carry',     s:'the soul behind you'},
    {t:'What is moving',     s:'the present current'},
    {t:'What is being born', s:'the star ahead'}
  ];
